Repository mojohaus/mojo-parent, pull requests merged in 2023-10, with the labels that each got.

#432 Update palantirJavaFormat for spotless - JDK 21 compatible
  pom.xml
Labels: enhancement, dependency-upgrade

#431 minimalMavenBuildVersion should not be overriding by mavenVersion
  pom.xml
Labels: bug

#433 Add dependencyManagement for maven-shade-plugin
  pom.xml
Labels: dependency-upgrade
